"""BibTeX file writer with manual stubs for not_found entries."""

from __future__ import annotations

from pathlib import Path

from .models import MatchResult, PaperQuery


def make_manual_stub(query: PaperQuery, marker: str = "TODO") -> str:
    """Generate a placeholder BibTeX entry for a query we couldn't resolve."""
    venue = (query.venue or "").lower()
    if any(kw in venue for kw in ("trans. graph", "journal", "ieee", "siam", "comput")):
        bib_type = "article"
    elif any(kw in venue for kw in ("siggraph", "sca", "mig", "eurographics",
                                    "conference", "proceedings", "symposium")):
        bib_type = "inproceedings"
    elif any(kw in venue for kw in ("dover", "springer", "press", "publisher")):
        bib_type = "book"
    else:
        bib_type = "misc"

    key = query.id or "unresolved"
    lines = [
        f"% {marker}: Manually verify this entry — not found in any source",
        f"@{bib_type}{{{key},",
        f"  title = {{{query.title}}},",
    ]
    if query.author:
        lines.append(f"  author = {{{query.author}}},")
    if query.year:
        lines.append(f"  year = {{{query.year}}},")
    if query.venue:
        venue_field = "journal" if bib_type == "article" else "booktitle"
        lines.append(f"  {venue_field} = {{{query.venue}}},")
    lines.append("}")
    return "\n".join(lines)


def write_bib_file(results: list[MatchResult], path: str | Path) -> None:
    """Write a .bib file containing all accepted matches and stubs for the rest.

    Sort order: accepted entries by canonical_key; unresolved by query id.
    """
    accepted = []
    unresolved = []
    for r in results:
        if r.chosen and r.chosen.bibtex and r.status in ("exact", "fuzzy_confirmed",
                                                          "fuzzy_pending"):
            accepted.append(r)
        else:
            unresolved.append(r)

    accepted.sort(key=lambda r: (r.canonical_key or "").lower())
    unresolved.sort(key=lambda r: (r.query.id or r.query.title).lower())

    out = Path(path)
    with out.open("w", encoding="utf-8") as f:
        f.write("% Auto-generated by bibtools\n")
        f.write("% Entries marked TODO require manual verification\n\n")

        for r in accepted:
            assert r.chosen and r.chosen.bibtex  # for mypy
            bib = r.chosen.bibtex.strip()
            if r.status == "fuzzy_pending":
                f.write("% TODO: fuzzy match, not user-confirmed\n")
            elif r.status == "fuzzy_confirmed":
                ms = "; ".join(r.mismatches)
                if ms:
                    f.write(f"% NOTE: fuzzy match (user confirmed): {ms}\n")
            f.write(bib)
            f.write("\n\n")

        for r in unresolved:
            if r.status == "fuzzy_rejected":
                marker = "REJECTED"
            elif r.status == "fuzzy_skipped":
                marker = "SKIPPED"
            else:
                marker = "TODO"
            f.write(make_manual_stub(r.query, marker=marker))
            f.write("\n\n")
